version: '3'
services:
  # Servicio de la base de datos MySQL
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grow-control
      MYSQL_USER: root
      MYSQL_PASSWORD: root
