spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grow-control?useSSL=false&characterEncoding=UTF-8
    username: gcapp
    password: gcpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

openia:
  apikey: dummy