spring:
  docker:
    compose:
      enabled: true
      file: docker-compose-dev.yml
  datasource:
    url: jdbc:mysql://localhost:3306/grow-control?useSSL=false&characterEncoding=UTF-8
    username: gcapp
    password: gcpass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 0
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

assistant:
  scan:
    packages: com.fg.grow_control.entity
  resetOnStart: true
  enabled: true
  name: AssisantGrowControl
  description: Service to interact with system through a text chat.
  openia:
    apikey: dummy

telegram:
  bot:
    enabled: true
    key: dummy

cors:
  allowed:
    origins: http://localhost:3000
    methods: GET,POST,PUT,DELETE